name: Sync to personal repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

      - name: Push to personal repository
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote add personal https://Andavidoc:${TOKEN}@github.com/Andavidoc/andres-davidocampo-portafolio.git
          git push personal main --force